name: flutter_icon_font_package_template
description: A template for creating icon font packs for Flutter
version: 0.0.1
author: Aaron Madlon-Kay <aaron@madlon-kay.com>
homepage: https://github.com/amake/flutter_icon_font_package_template/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf
